apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-frontend
spec:
  ingressClassName: nginx
  rules:
  - host: todo-frontend.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-frontend
            port:
              number: 80
