apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    app: todo-frontend
