apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
