apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    app: todo-backend
